### ISSUE TITLE
DSD Pop sound update in odroid C2 kernel

### ISSUE THREAD

**Issue by epicfrequency** [volumio/platform-odroid#16]
Hardkernel's Odroid C2's kernel has updated with DSD Pop fix. 

Can we update the Volume Odroid C2 kernel file to reflect this fix?

Thank you. 

https://github.com/hardkernel/linux/commit/d34872b4ef6dc5897e8869ab909a8af74589658b

ALSA: usb-audio: Eliminate noise at the start of DSD playback.
Copy mainline DSD playback pop noise fix

torvalds@0120073#diff-cc9fc192670bbec31122ad6874641755

[Problem]
In some USB DACs, a terrible pop noise comes to be heard
at the start of DSD playback (in the following situations).

- play first DSD track
- change from PCM track to DSD track
- change from DSD64 track to DSD128 track (and etc...)
- seek DSD track
- Fast-Forward/Rewind DSD track

[Cause]
At the start of playback, there is a little silence.
The silence bit pattern "0x69" is required on DSD mode,
but it is not like that.

[Solution]
This patch adds DSD silence pattern to the endpoint settings.

Signed-off-by: Nobutaka Okabe <nob77413@gmail.com>
Signed-off-by: Takashi Iwai <tiwai@suse.de>

**Comment by gkkpch** [comment]
Been taken care off, new version to be published soon under Community Portings, Volumio 2 for Odroid.
Also added support for a range of new DSD capable devices

**Comment by epicfrequency** [comment]
Thank you!
